name: "Check for changes in paths"

on:
  workflow_call:
    outputs:
      actions:
        value: ${{ jobs.changed.outputs.actions }}
      website:
        value: ${{ jobs.changed.outputs.website }}

permissions:
  contents: read
  pull-requests: read

jobs:
  changed:
    runs-on: ubuntu-22.04
    outputs:
      actions: ${{ steps.changes.outputs.actions }}
      website: ${{ steps.changes.outputs.website }}
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      # https://github.com/marketplace/actions/paths-changes-filter
      - name: Paths Changes Filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            actions:
              - '.github/workflows/*.yml'
            website:
              - 'public/**/*'
              - 'src/**/*'
              - '.tool-versions'
              - 'astro.config.mjs'
              - 'package.json'
              - 'tsconfig.json'
